=== AndreaVaiuso/lidobalneare/Lido/WebContent/xml/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
<xs:complexType name="Tdish">
	<xs:sequence>
		<xs:element name="name" type="xs:string" />
		<xs:element name="ingredients" type="xs:string" minOccurs="0" />
		<xs:element name="price" type="xs:float" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="Tcategory">
	<xs:sequence>
		<xs:element name="dish" type="Tdish" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" />
	<xs:attribute name="picture" type="xs:anyURI" />
	<xs:attribute name="description" type="xs:string" />
</xs:complexType>

<xs:element name="menu">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="category" type="Tcategory" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== AndreaVaiuso/lidobalneare/LidoBalneare/WebContent/xml/menu.xml
<?xml version="1.0" encoding="UTF-8" ?>

<menu
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="menu.xsd">
	
	<category name="Antipasti" picture="PIC" description="description">
		<dish>
			<name>Insalata caprese</name>
			<ingredients>Pomodoro, mozzarella di bufala.</ingredients>
			<price>5</price> <!-- Prezzi in euro -->
		</dish>
		
		<dish>
			<name>Tartine al salmone</name>
			<ingredients>Pane, salmone fresco, uova di salmone.</ingredients>
			<price>8.50</price>
		</dish>
	</category>
	
	<category name="Primi" picture="PIC" description="description">
		<dish>
			<name>Bucatini alle sarde</name>
			<ingredients>Sarde fresche, acciuga, finocchietto selvatico, pinoli, cipolla, uvetta.</ingredients>
			<price>12.50</price>
		</dish>
		
		<dish>
			<name>Mezze maniche alla carbonara</name>
			<ingredients>Guanciale affumicato, pecorino romano, tuorlo d'uova bio da galline allevate a terra, pepe nero.</ingredients>
			<price>999</price>
		</dish>
	</category>
	
	<category name="Secondi" picture="PIC" description="description">
		<dish>
			<name>Pesce spada arrosto</name>
			<ingredients>Filetto di pesce spada fresco, aglio, prezzemolo, olio extravergine d'oliva.</ingredients>
			<price>13</price>
		</dish>
		
		<dish>
			<name>Filetto di salmone</name>
			<ingredients>Filetto di salmone fresco, aglio, prezzemolo, olio extravergine d'oliva.</ingredients>
			<price>15</price>
		</dish>
	</category>
	
	<category name="Dolci" picture="PIC" description="description">
		<dish>
			<name>Macedonia di frutta</name>
			<ingredients>Ananas, fragole, pesca, melone bianco, cantalupo, kiwi, succo d'ananas.</ingredients>
			<price>4.50</price>
		</dish>
	</category>
	
	<category name="Bar" picture="PIC" description="description">
		<dish>
			<name>Caff√® espresso</name>
			<price>1.50</price>
		</dish>
		
		<dish>
			<name>Cono Algida</name>
			<price>2.50</price>
		</dish>
	</category>
</menu>

=== AndreaVaiuso/lidobalneare/Lido/WebContent/xml/menu.xml
<?xml version="1.0" encoding="UTF-8" ?>

<menu
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="menu.xsd">
	
	<category name="Appetizers">
		<dish>
			<name>Insalata caprese</name>
			<ingredients>Pomodoro, mozzarella di bufala.</ingredients>
			<price>5</price> <!-- Prezzi in euro -->
		</dish>
		
		<dish>
			<name>Tartine al salmone</name>
			<ingredients>Pane, salmone fresco, uova di salmone.</ingredients>
			<price>8.50</price>
		</dish>
	</category>
	
	<category name="First dishes">
		<dish>
			<name>Bucatini alle sarde</name>
			<ingredients>Sarde fresche, acciuga, finocchietto selvatico, pinoli, cipolla, uvetta.</ingredients>
			<price>12.50</price>
		</dish>
		
		<dish>
			<name>Mezze maniche alla carbonara</name>
			<ingredients>Guanciale affumicato, pecorino romano, tuorlo d'uova bio da galline allevate a terra, pepe nero.</ingredients>
			<price>99.99</price>
		</dish>
	</category>
	
	<category name="Second dishes">
		<dish>
			<name>Filetto di pesce spada</name>
			<ingredients>Filetto di pesce spada fresco, aglio, prezzemolo, olio extravergine d'oliva.</ingredients>
			<price>13</price>
		</dish>
		
		<dish>
			<name>Filetto di salmone</name>
			<ingredients>Filetto di salmone fresco, aglio, prezzemolo, olio extravergine d'oliva.</ingredients>
			<price>15</price>
		</dish>
	</category>
	
	<category name="Desserts">
		<dish>
			<name>Macedonia di frutta</name>
			<ingredients>Ananas, fragole, pesca, melone bianco, cantalupo, kiwi, succo d'ananas.</ingredients>
			<price>4.50</price>
		</dish>
	</category>
	
	<category name="Bar">
		<dish>
			<name>Caff√® espresso</name>
			<price>1.50</price>
		</dish>
		
		<dish>
			<name>Cornetto Algida</name>
			<price>2.50</price>
		</dish>
	</category>
</menu>
